const d=new Date();
const appById=id=>document.getElementById(id);
function toast(message){const el=appById('toast');if(!el)return;el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('siddha-theme',document.body.classList.contains('dark')?'dark':'light')}
if(localStorage.getItem('siddha-theme')==='dark')document.body.classList.add('dark');
const dateEl=appById('todayDate');if(dateEl)dateEl.textContent=d.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
const title=appById('todayTitle');if(title){const h=d.getHours();title.textContent=h<12?'Good morning':'Good '+(h<17?'afternoon':'evening')}
(function(){const key='siddha-zoom',min=.8,max=2,step=.1;const get=()=>{const n=Number(localStorage.getItem(key));return Number.isFinite(n)?Math.min(max,Math.max(min,n)):1};const apply=v=>{v=Math.min(max,Math.max(min,Math.round(v*10)/10));document.documentElement.style.setProperty('--page-zoom',v);localStorage.setItem(key,String(v));const el=appById('zoomValue');if(el)el.textContent=Math.round(v*100)+'%'};function build(){if(appById('readabilityControls'))return;const box=document.createElement('div');box.id='readabilityControls';box.className='readability-controls';box.innerHTML='<button type="button" id="zoomOut">A−</button><span id="zoomValue">100%</span><button type="button" id="zoomIn">A+</button><button type="button" id="zoomReset">↺</button>';document.body.appendChild(box);appById('zoomOut').onclick=()=>apply(get()-step);appById('zoomIn').onclick=()=>apply(get()+step);appById('zoomReset').onclick=()=>apply(1);apply(get())}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build,{once:true});else build()})();
(function(){const originalFetch=window.fetch.bind(window);window.fetch=function(input,init){try{const raw=typeof input==='string'?input:input.url;if(raw&&raw.includes('nityapanchangam.com/api/panchangam.php')){const source=new URL(raw);const proxy=new URL('/api/panchangam',window.location.origin);source.searchParams.forEach((value,key)=>proxy.searchParams.set(key,key==='lng'?'lon':key==='lat'?'lat':key==='date'?'date':key));return originalFetch(proxy.toString(),init)}}catch(error){console.warn('Panchangam proxy routing failed',error)}return originalFetch(input,init)}})();
(function(){
const TELUGU={Pratipada:'పాడ్యమి',Dwitiya:'విదియ',Tritiya:'తదియ',Chaturthi:'చవితి',Panchami:'పంచమి',Shashthi:'షష్టి',Saptami:'సప్తమి',Ashtami:'అష్టమి',Navami:'నవమి',Dashami:'దశమి',Ekadashi:'ఏకాదశి',Dwadashi:'ద్వాదశి',Trayodashi:'త్రయోదశి',Chaturdashi:'చతుర్దశి',Purnima:'పౌర్ణమి',Amavasya:'అమావాస్య',Ashwini:'అశ్విని',Bharani:'భరణి',Krittika:'కృత్తిక',Rohini:'రోహిణి',Mrigashira:'మృగశిర',Ardra:'ఆర్ద్ర',Punarvasu:'పునర్వసు',Pushya:'పుష్యమి',Ashlesha:'ఆశ్లేష',Magha:'మఘ','Purva Phalguni':'పుబ్బ','Uttara Phalguni':'ఉత్తర ఫల్గుణి',Hasta:'హస్త',Chitra:'చిత్త',Swati:'స్వాతి',Vishakha:'విశాఖ',Anuradha:'అనూరాధ',Jyeshtha:'జ్యేష్ఠ',Mula:'మూల','Purva Ashadha':'పూర్వాషాఢ','Uttara Ashadha':'ఉత్తరాషాఢ',Shravana:'శ్రవణం',Dhanishta:'ధనిష్ఠ',Shatabhisha:'శతభిషం','Purva Bhadrapada':'పూర్వాభాద్ర','Uttara Bhadrapada':'ఉత్తరాభాద్ర',Revati:'రేవతి',Mesha:'మేషం',Vrishabha:'వృషభం',Mithuna:'మిథునం',Karkataka:'కర్కాటకం',Simha:'సింహం',Kanya:'కన్య',Tula:'తుల',Vrishchika:'వృశ్చికం',Dhanus:'ధనుస్సు',Makara:'మకరం',Kumbha:'కుంభం',Meena:'మీనం'};
function bi(v){const raw=String(v||'—').trim();if(!raw||raw==='—'||raw.includes('/'))return raw||'—';return TELUGU[raw]?raw+' / '+TELUGU[raw]:raw}
function applyNames(){[['todayTithi',false],['todayNakshatra',false],['todayRashi',false]].forEach(([id])=>{const el=appById(id);if(!el)return;const raw=el.dataset.originalValue||el.textContent.trim();if(raw==='Calculating…'||raw==='Calculating...')return;if(!el.dataset.originalValue)el.dataset.originalValue=raw;el.textContent=bi(raw)})}
function emergencyFallback(){const values={todayTithi:'Data unavailable / సమాచారం లభ్యం కాదు',todayNakshatra:'Data unavailable / సమాచారం లభ్యం కాదు',todayRashi:'Data unavailable / సమాచారం లభ్యం కాదు',todayYogaKarana:'Data unavailable / సమాచారం లభ్యం కాదు'};Object.keys(values).forEach(id=>{const el=appById(id);if(el&&/^Calculating/.test(el.textContent.trim()))el.textContent=values[id]});const times=['tithiTimes','sunTimes','rahuTimes','gulikaTimes','amruthaTimes','muhurtaTimes','todayTarabala','todayChandrabala'];times.forEach(id=>{const el=appById(id);if(el&&/^Calculating/.test(el.textContent.trim()))el.textContent='Data unavailable / సమాచారం లభ్యం కాదు'});['horaMorning','horaEvening'].forEach(id=>{const el=appById(id);if(el&&/^Calculating/.test(el.textContent.trim()))el.textContent='Data unavailable / సమాచారం లభ్యం కాదు'});toast('Live Panchangam data is unavailable. Please retry.');}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',applyNames,{once:true});else applyNames();window.addEventListener('load',()=>{applyNames();setTimeout(applyNames,1000);setTimeout(applyNames,2500);setTimeout(emergencyFallback,10000)})
})();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
window.enableSiddhaNotifications=async()=>false;
