(()=>{
const NAKSHATRAS=['Ashwini','Bharani','Krittika','Rohini','Mrigashira','Ardra','Punarvasu','Pushya','Ashlesha','Magha','Purva Phalguni','Uttara Phalguni','Hasta','Chitra','Swati','Vishakha','Anuradha','Jyeshtha','Mula','Purva Ashadha','Uttara Ashadha','Shravana','Dhanishta','Shatabhisha','Purva Bhadrapada','Uttara Bhadrapada','Revati'];
const RASHIS=['Mesha','Vrishabha','Mithuna','Karkataka','Simha','Kanya','Tula','Vrishchika','Dhanus','Makara','Kumbha','Meena'];
const TELUGU_NAK=['అశ్విని','భరణి','కృత్తిక','రోహిణి','మృగశిర','ఆర్ద్ర','పునర్వసు','పుష్యమి','ఆశ్లేష','మఘ','పుబ్బ','ఉత్తర ఫల్గుణి','హస్త','చిత్త','స్వాతి','విశాఖ','అనూరాధ','జ్యేష్ఠ','మూల','పూర్వాషాఢ','ఉత్తరాషాఢ','శ్రవణం','ధనిష్ఠ','శతభిషం','పూర్వాభాద్ర','ఉత్తరాభాద్ర','రేవతి'];
const TELUGU_RASHI=['మేషం','వృషభం','మిథునం','కర్కాటకం','సింహం','కన్య','తుల','వృశ్చికం','ధనుస్సు','మకరం','కుంభం','మీనం'];
const VARA=[['Sunday','ఆదివారం'],['Monday','సోమవారం'],['Tuesday','మంగళవారం'],['Wednesday','బుధవారం'],['Thursday','గురువారం'],['Friday','శుక్రవారం'],['Saturday','శనివారం']];
const TARA=[['Janma Tara','Mixed','జన్మ తార'],['Sampat Tara','Very Good','సంపత్ తార'],['Vipat Tara','Bad','విపత్ తార'],['Kshema Tara','Good','క్షేమ తార'],['Pratyak Tara','Bad','ప్రత్యక్ తార'],['Sadhaka Tara','Very Good','సాధక తార'],['Vadha Tara','Very Bad','వధ తార'],['Mitra Tara','Good','మిత్ర తార'],['Parama Mitra Tara','Excellent','పరమ మిత్ర తార']];
const bi=(english,telugu='')=>({english:String(english||'Unavailable'),telugu:String(telugu||'')});
const text=v=>typeof v==='string'||typeof v==='number'?String(v):Array.isArray(v)?v.map(text).filter(Boolean).join(', '):v&&typeof v==='object'?[v.name,v.english,v.display,v.value,v.title,v.label,[v.start,v.end].filter(Boolean).join(' – ')].find(Boolean)||'':'';
const telugu=v=>v&&typeof v==='object'?(v.telugu||v.teluguName||v.te||''):'';
const val=(...xs)=>{for(const x of xs){const t=text(x);if(t)return t}return 'Unavailable'};
const timing=v=>{if(Array.isArray(v))return v.map(timing).filter(Boolean).join(', ');if(v&&typeof v==='object'){const name=v.name||v.title||v.label||'';const start=v.start||v.startAt||v.startsAt||v.startLocal||'';const end=v.end||v.endAt||v.endsAt||v.endLocal||'';return [name,[start,end].filter(Boolean).join(' – ')].filter(Boolean).join(': ')||text(v)}return text(v)};
const stored=()=>{try{return JSON.parse(localStorage.getItem('siddha-panchang-result')||'null')}catch{return null}};
function fallback(iso,error){const d=new Date(`${iso}T12:00:00+05:30`),v=VARA[d.getDay()];return{date:iso,vara:bi(v[0],v[1]),paksha:bi(),masa:bi(),samvatsara:bi(),tithi:{name:'Unavailable'},nakshatra:bi(),rashi:bi(),yoga:{name:'Unavailable'},karana:{name:'Unavailable'},sunrise:'06:00',sunset:'18:00',amruthaGhadia:'Unavailable',abhijithLagna:'Unavailable',durmuhurtha:'Unavailable',yamaganda:'Unavailable',gulika:'Unavailable',hora:'Unavailable',tarabalam:'Unavailable',chandrabalam:'Unavailable',dataSource:'Panchangam API unavailable',error,location:{name:'Hyderabad',timezone:'Asia/Kolkata'}}}
function normalize(raw,iso){const root=raw?.data||raw?.panchangam||raw?.result||raw||{};const a=root.astronomical||root;const t=a.tithi||{},n=a.nakshatra||{},y=a.yoga||{},k=a.karana||{};const r=a.rasi||a.rashi||a.moonRasi||a.moon_rashi||{};const tn=val(t,a.tithi_name),nn=val(n,a.nakshatra_name),rn=val(r,a.rashi_name,a.moon_rashi_name);const ni=NAKSHATRAS.findIndex(x=>x.toLowerCase()===nn.toLowerCase()),ri=RASHIS.findIndex(x=>x.toLowerCase()===rn.toLowerCase());const weekday=new Date(`${iso}T12:00:00+05:30`).getDay();const vara=a.vara||{};const masa=a.masa||a.lunarMonth||{};const sam=a.samvatsara||a.samvat||{};const field=(...keys)=>{for(const key of keys){const value=a[key]??root[key];const rendered=timing(value);if(rendered)return rendered}return 'Unavailable'};return{date:iso,vara:bi(val(vara)||VARA[weekday][0],telugu(vara)),paksha:bi(val(t.paksha,a.paksha),telugu(t.paksha)||telugu(a.paksha)),masa:bi(val(masa,a.amantaMasa,a.lunarMonth),telugu(masa)||telugu(a.amantaMasa)),samvatsara:bi(val(sam,a.samvatsara_name),telugu(sam)||telugu(a.samvatsara_name)),tithi:{name:tn,start:t.startsAt||t.startAt||t.start||'',end:t.endsAt||t.endAt||t.end||''},nakshatra:bi(nn,telugu(n)||(ni>=0?TELUGU_NAK[ni]:'')),rashi:bi(rn,telugu(r)||(ri>=0?TELUGU_RASHI[ri]:'')),yoga:{name:val(y,a.yoga_name)},karana:{name:val(k,a.karana_name)},sunrise:field('sunrise','sunRise','sunriseTime'),sunset:field('sunset','sunSet','sunsetTime'),amruthaGhadia:field('amruthaGhadia','amritaGadiya','amritakala','amrita_ghadiya'),abhijithLagna:field('abhijithLagna','abhijitMuhurta','abhijit_lagna'),durmuhurtha:field('durmuhurtha','durmuhurtam','durmuhurtham'),yamaganda:field('yamaganda','yamaGandam','yamagandam'),gulika:field('gulika','gulikaKalam','gulika_kalam'),hora:field('hora','horaMuhurta','hora_muhurta'),dataSource:'Hyderabad Panchangam API + local timing fallbacks',location:{name:'Hyderabad',latitude:17.385,longitude:78.4867,timezone:'Asia/Kolkata'}}}
async function calculate(iso){try{const response=await fetch(`/api/panchangam?date=${encodeURIComponent(iso)}&lat=17.385&lng=78.4867`,{cache:'no-store',headers:{accept:'application/json'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const result=normalize(await response.json(),iso);localStorage.setItem('siddha-panchang-result',JSON.stringify(result));window.SIDDHA_PANCHANG=result;return result}catch(error){const result=fallback(iso,error?.message||'Request failed');window.SIDDHA_PANCHANG=result;return result}}
function indexOfName(value,list){const s=String(value||'').toLowerCase().replace(/[^a-z]/g,'');return list.findIndex(x=>x.toLowerCase().replace(/[^a-z]/g,'')===s)}
function tarabalam(birth,daily){const b=indexOfName(birth,NAKSHATRAS),d=indexOfName(daily,NAKSHATRAS);if(b<0||d<0)return 'Select birth Nakshatra';const pos=((d-b+27)%27)+1;const t=TARA[(pos-1)%9];return `${t[0]} — ${t[1]} (${pos}/27)`}
function chandrabalam(birth,daily){const b=indexOfName(birth,RASHIS),d=indexOfName(daily,RASHIS);if(b<0||d<0)return 'Select birth Rashi';const house=((d-b+12)%12)+1;const good=[1,3,6,7,10,11].includes(house);return `${good?'Favourable':'Unfavourable'} — ${house}th from birth Rashi`}
function hora(sunrise,sunset,weekday){const parse=s=>{const m=String(s||'').match(/(\d{1,2}):(\d{2})\s*([AP]M)?/i);if(!m)return null;let h=+m[1]%12;if((m[3]||'').toUpperCase()==='PM')h+=12;return h*60+ +m[2]};const r=parse(sunrise),s=parse(sunset);if(r==null||s==null)return 'Unavailable';const day=(s-r)/12;const night=120/12;const planets=['Sun','Venus','Mercury','Moon','Saturn','Jupiter','Mars'];const order=[0,1,2,3,4,5,6];const start=weekday%7;const morning=Array.from({length:12},(_,i)=>`${String(Math.floor((r+i*day)/60)%24).padStart(2,'0')}:${String(Math.floor((r+i*day)%60)).padStart(2,'0')} – ${String(Math.floor((r+(i+1)*day)/60)%24).padStart(2,'0')}:${String(Math.floor((r+(i+1)*day)%60)).padStart(2,'0')} (${planets[(start+i*order[0])%7]})`);const evening=Array.from({length:12},(_,i)=>`${String(Math.floor((s+i*night)/60)%24).padStart(2,'0')}:${String(Math.floor((s+i*night)%60)).padStart(2,'0')} – ${String(Math.floor((s+(i+1)*night)/60)%24).padStart(2,'0')}:${String(Math.floor((s+(i+1)*night)%60)).padStart(2,'0')} (${planets[(start+12+i)%7]})`);return `Morning: ${morning.join(', ')} | Evening/Night: ${evening.join(', ')}`}
window.SiddhaPanchangEngine={nakshatras:NAKSHATRAS,rashis:RASHIS,calculate,getStored:stored,tarabalam,chandrabalam,hora};
})();