(() => {
  const NAKSHATRAS=['Ashwini','Bharani','Krittika','Rohini','Mrigashira','Ardra','Punarvasu','Pushya','Ashlesha','Magha','Purva Phalguni','Uttara Phalguni','Hasta','Chitra','Swati','Vishakha','Anuradha','Jyeshtha','Mula','Purva Ashadha','Uttara Ashadha','Shravana','Dhanishta','Shatabhisha','Purva Bhadrapada','Uttara Bhadrapada','Revati'];
  const RASHIS=['Mesha','Vrishabha','Mithuna','Karkataka','Simha','Kanya','Tula','Vrishchika','Dhanus','Makara','Kumbha','Meena'];
  const VARA=[['Sunday','ఆదివారం'],['Monday','సోమవారం'],['Tuesday','మంగళవారం'],['Wednesday','బుధవారం'],['Thursday','గురువారం'],['Friday','శుక్రవారం'],['Saturday','శనివారం']];
  const TARA_NAMES=[['Janma','జన్మ'],['Sampat','సంపత్'],['Vipat','విపత్'],['Kshema','క్షేమ'],['Pratyak','ప్రత్యక్'],['Sadhana','సాధన'],['Naidhana','నైధన'],['Mitra','మిత్ర'],['Param Mitra','పరమ మిత్ర']];
  const TARA_GOOD=[2,4,6,8,9],CHANDRA_GOOD=[1,3,6,7,10,11];
  const dateObj=iso=>new Date(`${iso}T12:00:00+05:30`);
  const timeToMinutes=t=>{if(!t)return null;const m=String(t).match(/(\d{1,2}):?(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null};
  const fmt=n=>`${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
  function segment(sr,ss,index){const len=(ss-sr)/8;return `${fmt(sr+index*len)} – ${fmt(sr+(index+1)*len)}`}
  function calculateTimings(iso,sunrise='06:00',sunset='18:00',weekday){const sr=timeToMinutes(sunrise)??360,ss=timeToMinutes(sunset)??1080,wd=weekday??dateObj(iso).getDay();return{gulikaKalam:segment(sr,ss,[6,5,4,3,2,1,0][wd]),yamagandam:segment(sr,ss,[4,3,2,1,0,6,5][wd]),rahuKalam:segment(sr,ss,[1,6,4,5,3,2,7][wd]),amruthaGhadika:segment(sr,ss,([6,5,4,3,2,1,0][wd]+3)%8)}}
  function taraBala(birth,day){const b=NAKSHATRAS.indexOf(birth),d=NAKSHATRAS.indexOf(day);if(b<0||d<0)return null;const number=((d-b+27)%27)%9+1,name=TARA_NAMES[number-1];return{number,name:name[0],telugu:name[1],favourable:TARA_GOOD.includes(number),verdict:TARA_GOOD.includes(number)?'Favourable / శుభం':number===1?'Mixed / మిశ్రమం':'Unfavourable / అశుభం'}}
  function chandraBala(birth,day){const b=RASHIS.indexOf(birth),d=RASHIS.indexOf(day);if(b<0||d<0)return null;const house=((d-b+12)%12)+1;return{house,favourable:CHANDRA_GOOD.includes(house),verdict:CHANDRA_GOOD.includes(house)?'Favourable / శుభం':'Unfavourable / అశుభం'}}
  function makeSelect(id,label,items,storageKey){const wrap=document.createElement('label');wrap.className='bala-selector';wrap.innerHTML=`<span>${label}</span><select id="${id}" aria-label="${label}">${items.map(n=>`<option value="${n}">${n}</option>`).join('')}</select>`;const saved=localStorage.getItem(storageKey);if(saved&&items.includes(saved))wrap.querySelector('select').value=saved;wrap.querySelector('select').addEventListener('change',()=>{localStorage.setItem(storageKey,wrap.querySelector('select').value);window.dispatchEvent(new Event('siddha-birth-change'));});return wrap}
  function ensureBirthForm(){const taraHost=document.getElementById('taraSelector');const chandraHost=document.getElementById('chandraSelector');if(!taraHost||!chandraHost)return;if(!taraHost.children.length)taraHost.appendChild(makeSelect('birthNakshatra','Birth Nakshatra / జన్మ నక్షత్రం',NAKSHATRAS,'siddha-birth-nakshatra'));if(!chandraHost.children.length)chandraHost.appendChild(makeSelect('birthRashi','Birth Rashi / జన్మ రాశి',RASHIS,'siddha-birth-rashi'));}
  function fromStored(){try{return JSON.parse(localStorage.getItem('siddha-panchang-result')||'null')}catch(e){return null}}
  async function fetchLive(iso){const saved=JSON.parse(localStorage.getItem('siddha-location')||'null');const lat=Number(saved?.lat)||17.385,lon=Number(saved?.lon)||78.4867;const url=`https://nityapanchangam.com/api/panchangam.php?date=${iso}&lat=${lat}&lng=${lon}`;const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw Error(`API ${response.status}`);const data=await response.json();return{data,nakshatra:data.nakshatra?.name||data.nakshatra?.english||'',rashi:data.rashi?.name||data.chandra_rashi?.name||data.moonsign?.name||'',sunrise:data.sun?.sunrise||data.sunrise||'06:00',sunset:data.sun?.sunset||data.sunset||'18:00'}}
  async function calculate(iso){ensureBirthForm();const d=dateObj(iso),wd=d.getDay(),vara=VARA[wd],stored=fromStored();let live=null;try{live=await fetchLive(iso)}catch(e){console.warn('Live Panchang unavailable',e)}const dayNakshatra=live?.nakshatra||stored?.currentMoon?.nakshatra||'Uttara Phalguni';const dayRashi=live?.rashi||stored?.currentMoon?.rashi||'Kanya';const birthNakshatra=localStorage.getItem('siddha-birth-nakshatra')||'Anuradha',birthRashi=localStorage.getItem('siddha-birth-rashi')||'Vrishchika';const timings=calculateTimings(iso,live?.sunrise,live?.sunset,wd);const result={date:iso,vara:{english:vara[0],telugu:vara[1]},paksha:{english:'Shukla Paksha',telugu:'శుక్ల పక్షం'},masa:{english:'Bhadrapada',telugu:'భాద్రపదం'},samvatsara:{english:'Parabhava',telugu:'పరాభవ'},tithi:{name:live?.data?.tithi?.name||'Pratipada / పాడ్యమి',start:live?.data?.tithi?.start||'—',end:live?.data?.tithi?.end||'—'},nakshatra:{english:dayNakshatra,telugu:dayNakshatra},rashi:{english:dayRashi,telugu:dayRashi},yoga:{name:live?.data?.yoga?.name||'—'},karana:{name:live?.data?.karana?.name||'—'},sunrise:live?.sunrise||'06:00',sunset:live?.sunset||'18:00',...timings,tarabala:taraBala(birthNakshatra,dayNakshatra),chandrabala:chandraBala(birthRashi,dayRashi),birthProfile:{nakshatra:birthNakshatra,rashi:birthRashi},currentMoon:{nakshatra:dayNakshatra,rashi:dayRashi},dataSource:live?'Live API':'Fallback',location:{name:'Hyderabad',timezone:'Asia/Kolkata'}};localStorage.setItem('siddha-panchang-result',JSON.stringify(result));window.SIDDHA_PANCHANG=result;return result}
  window.SiddhaPanchangEngine={nakshatras:NAKSHATRAS,rashis:RASHIS,getStored:fromStored,setResult:r=>{localStorage.setItem('siddha-panchang-result',JSON.stringify(r));window.SIDDHA_PANCHANG=r;return r},calculate,taraBala,chandraBala};
})();